TEST_PLAYER1 = '👻'
TEST_PLAYER2 = '🎃'
TEST_EMPTY = '🔳'
TEST_THREE_EMPTY = "#{TEST_EMPTY}#{TEST_EMPTY}#{TEST_EMPTY}"
TEST_DEFAULT_INPUT_REQUEST = "Please enter your move: "
TEST_WELCOME_MESSAGE = "Welcome to SCARY tic tac toe!! #{TEST_PLAYER2} vs #{TEST_PLAYER1} "
TEST_WRONG_INPUT = "Move invalid - please try again: "
TEST_DRAW = "😭😭😭 IT'S A DRAW! 😭😭😭"
TEST_PLAYER1_WIN = "🎉🥳🎉🥳🎉🥳 #{TEST_PLAYER1} WINS! 🎉🥳🎉🥳🎉🥳"
TEST_PLAYER2_WIN = "🎉🥳🎉🥳🎉🥳 #{TEST_PLAYER2} WINS! 🎉🥳🎉🥳🎉🥳"
TEST_PLAYER1_TURN = "It's #{TEST_PLAYER1}'s turn! "