TEST_PLAYER1 = '👻'
TEST_PLAYER2 = '🎃'
TEST_EMPTY = '🔳'
TEST_THREE_EMPTY = "#{TEST_EMPTY}#{TEST_EMPTY}#{TEST_EMPTY}"
TEST_DEFAULT_INPUT_REQUEST = "Please enter your move: "
TEST_WELCOME_MESSAGE = "Welcome to SCARY tic tac toe!! #{TEST_PLAYER2} vs #{TEST_PLAYER1} "